[server]
address=":19091"

[database]
driver = "mysql"
dsn = "root:mysql@123@tcp(192.168.48.10:3306)/aiops_dev?charset=utf8&parseTime=True"

[prometheus]
prometheusUrl = "http://localhost:9090"
prometheusConfigPath = "./prometheus.yml"
alertRulesConfigPath = "./alert_rules.yml"
