[server]
address=":19091"

[database]
driver = "mysql"
dsn = "root:mysql@123@tcp(192.168.48.10:3306)/aiops_dev?charset=utf8&parseTime=True"

[prometheus]
prometheusUrl = "http://localhost:9090"
prometheusBasePath = "/Users/renzhiqiang/Workspace/self_lab/prometheus/prometheus-2.34.0.darwin-arm64"
prometheusConfigPath = "/Users/renzhiqiang/Workspace/self_lab/prometheus/prometheus-2.34.0.darwin-arm64/prometheus.yml"
alertRulesConfigPath = "./alert_rules.yml"
