---
- name: Configure prometheus yml
  template:
    src: "prometheus.yml.j2"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    force: true
    owner: root
    group: root
    mode: 0640
    validate: "{{ prometheus_base_dir }}/promtool check config %s"
  notify:
    - reload prometheus